---
- hosts: webservers
  # remote_user is ignored by packer.
  remote_user: ubuntu
  become: yes
  tasks:
    - name: full-upgrade
      apt:
        upgrade: full
        update_cache: yes
        state: latest

    - name: ensure apache is at the latest version
      apt:
        name: apache2
        state: latest

    - name: ensure apache is enabled at boot
      service: name=apache2 enabled=yes
